[package]
name = "crulz"
version = "0.0.1"
authors = ["Erik Zscheile <erik.zscheile@gmail.com>"]
edition = "2018"
exclude = ["docs/bench_results**.txt","*.sh"]
repository = "https://github.com/zserik/crulz-rs"

[dependencies]
clap = "~2.33"
failure = "0.1.5"
rayon = "1.1"
readfilez = "0.1"
