[package]
name = "crulz"
description = "a rust implementation of the 'crulz' macro language interpreter"
version = "0.0.3"
authors = ["Erik Zscheile <erik.zscheile@gmail.com>"]
edition = "2018"
exclude = ["docs/bench_results*.txt","*.sh"]
repository = "https://github.com/zserik/crulz-rs"
license = "MIT OR Apache-2.0"
build = "build.rs"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
bincode = { version = "1.2", optional = true }
cfg-if = "0.1"
clap = "2.33"
codespan = "0.5"
codespan-reporting = "0.5"
delegate = "0.3"
flate2 = { version = "1.0", optional = true }
itertools = "0.8"
phf = { version = "0.8", features = ["macros"] }
readfilez = "0.2"
serde = { version = "1.0", features = ["derive"] }
string_cache = "0.8"

[build-dependencies]
string_cache_codegen = "0.5"

[features]
compile = [ "bincode", "flate2" ]

[profile.release]
lto = true
