name: Rust

on: [push, pull_request]

env:
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
          - stable
          - 1.40.0
    steps:
      - uses: actions/checkout@v2
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.OS }}-build-
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add rustfmt
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ runner.OS }}-nightly-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.OS }}-nightly-build-
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench
